import type { Template } from "./types";
import type { TemplateId } from "@/lib/schema";

export const TEMPLATES: Record<TemplateId, Template> = {
  classic: {
    id: "classic",
    name: "Classic",
    description: "Garamond, centered name, ruled headings — finance/legal",
    font: { heading: "Garamond", body: "Garamond" },
    nameStyle: { size: 22, align: "center" },
    headingStyle: "rule-below",
    divider: "thin",
    accentUse: "headings",
    density: "standard",
    bullet: "dot",
  },
  modern: {
    id: "modern",
    name: "Modern",
    description: "Calibri, spaced-caps headings — tech/general",
    font: { heading: "Calibri", body: "Calibri" },
    nameStyle: { size: 20, align: "left" },
    headingStyle: "spaced-caps",
    divider: "thin",
    accentUse: "headings",
    density: "standard",
    bullet: "dot",
  },
  compact: {
    id: "compact",
    name: "Compact",
    description: "Arial, tight spacing — fit one page",
    font: { heading: "Arial", body: "Arial" },
    nameStyle: { size: 18, align: "left" },
    headingStyle: "plain-bold",
    divider: "none",
    accentUse: "none",
    density: "compact",
    bullet: "dash",
  },
  minimal: {
    id: "minimal",
    name: "Minimal",
    description: "Airy, tracked caps, no rules",
    font: { heading: "Calibri", body: "Calibri" },
    nameStyle: { size: 20, align: "center", tracking: 2 },
    headingStyle: "spaced-caps",
    divider: "none",
    accentUse: "none",
    density: "airy",
    bullet: "dot",
  },
  "bold-name": {
    id: "bold-name",
    name: "Bold Name",
    description: "Large accent name, thick rule",
    font: { heading: "Arial", body: "Arial" },
    nameStyle: { size: 26, align: "left", accent: true },
    headingStyle: "rule-thick",
    divider: "thick",
    accentUse: "headings+name",
    density: "standard",
    bullet: "square",
  },
  executive: {
    id: "executive",
    name: "Executive",
    description: "Georgia, small-caps headings",
    font: { heading: "Georgia", body: "Georgia" },
    nameStyle: { size: 22, align: "center" },
    headingStyle: "small-caps",
    divider: "thin",
    accentUse: "headings",
    density: "standard",
    bullet: "dot",
  },
  underlined: {
    id: "underlined",
    name: "Underlined",
    description: "Underline headings, accent dates",
    font: { heading: "Cambria", body: "Cambria" },
    nameStyle: { size: 20, align: "left" },
    headingStyle: "underline",
    divider: "none",
    accentUse: "headings+dates",
    density: "standard",
    bullet: "dot",
  },
  "two-tone": {
    id: "two-tone",
    name: "Two-Tone",
    description: "Accent headings + dates",
    font: { heading: "Calibri", body: "Calibri" },
    nameStyle: { size: 20, align: "left", accent: false },
    headingStyle: "rule-below",
    divider: "thin",
    accentUse: "headings+dates",
    density: "standard",
    bullet: "dot",
  },
  detailed: {
    id: "detailed",
    name: "Detailed",
    description: "Georgia, airy — education/research",
    font: { heading: "Georgia", body: "Georgia" },
    nameStyle: { size: 20, align: "left" },
    headingStyle: "rule-below",
    divider: "thin",
    accentUse: "headings",
    density: "airy",
    bullet: "dot",
  },
  "simple-sans": {
    id: "simple-sans",
    name: "Simple Sans",
    description: "Pure B/W Arial — max ATS safety",
    font: { heading: "Arial", body: "Arial" },
    nameStyle: { size: 18, align: "left" },
    headingStyle: "plain-bold",
    divider: "none",
    accentUse: "none",
    density: "standard",
    bullet: "dot",
  },
};
